services:
  app:
    build:
      context: .
    image: ${DOCKER_IMAGE}
    ports:
      - "${SPRINGDRASIL_PORT}:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      BASE_DOMAIN_URL: ${BASE_DOMAIN_URL}
      SERVER_FORWARD_HEADERS_STRATEGY: ${SERVER_FORWARD_HEADERS_STRATEGY:-framework}
      YGGDRASIL_SIGNATURE_PRIVATE_KEY: ${YGGDRASIL_SIGNATURE_PRIVATE_KEY}
      YGGDRASIL_SIGNATURE_PUBLIC_KEY: ${YGGDRASIL_SIGNATURE_PUBLIC_KEY}
    depends_on:
      - postgres

  postgres:
    image: postgres:18.4
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres18-data:/var/lib/postgresql

volumes:
  postgres18-data:
