spring:
  application:
    name: springdrasil

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

custom:
  sessionTokenTimeout: ${SESSION_TIMEOUT:10d}